### ISSUE TITLE
Randomness 

### ISSUE THREAD

**Issue by TGLS** [ArtemGr/Sidekick#252] opened 2020-06-05 16:26 UTC
Hi, there's some questions about how random the dice bot is on a server I frequent. Really improbable rolls seem to frequently. Would it be possible to provide dice rolling code/pseudocode for inspection?

**Comment by ArtemGr** [comment] 2020-06-05 17:00
Possible, but not a priority right now. Duplicate of #10

**Closed by ArtemGr** 2020-06-05 17:00 UTC
