### ISSUE TITLE
sidekick#6198 delayed rolling

### ISSUE THREAD

**Issue by MusingStar** [ArtemGr/Sidekick#120] opened 2018-05-28 19:40 UTC
It takes minutes, we're talking 2 to 8 minutes for the bot to acknowledge /r strings in our server on discord before it will post the result of the roll.

So we are setting up the string correctly, but the issue is that the sidekick is taking far too long to acknowledge the rolls.
https://scontent-ort2-1.xx.fbcdn.net/v/t1.0-9/33714951_443128092800296_1975248372734361600_n.jpg?_nc_cat=0&oh=4f8c4aefbb5add47d40d104cd070eb1e&oe=5B825737

**Comment by Jallen1906** [comment] 2018-05-28 20:10
Same here - we've seen this before but not for a few weeks.

**Comment by ArtemGr** [comment] 2018-05-28 21:11
Works fine for me: https://www.screencast.com/t/FTM5x5fXK5l.

Feel free to send me the exact time (GMT or with a time zone), up to a second, when you were seeing the slowness. I'll check the logs then.

If you can reproduce this always or often then it also makes sense to invite me to whenever you see this in order for me to test this live.

Discord is a large cloud of servers and Sidekick is a cluster of 32 shard processes (on each of the HA servers), there might be slowdowns both in the Discord cloud and in the bot that one wouldn't see outside of a given server.

**Comment by MusingStar** [comment] 2018-05-29 00:45
By all means! It's doing it right now.

https://discord.gg/dMX3jt

**Comment by MusingStar** [comment] 2018-05-29 01:10
Its about the same time two nights in a row.. about 730 PM CST and onward. First its a few seconds, then about thirty, then minutes. 

We run a dice based roleplaying group and doing sequential instance of posting text and then rolling dice for the outcome.

**Comment by ArtemGr** [comment] 2018-06-02 22:21
So we looked into this and looks like the problem was temporary. Closing for now, feel free to reopen if the problem resurfaces.

**Closed by ArtemGr** 2018-06-02 22:21 UTC

**Comment by ArtemGr** [comment] 2018-07-08 16:08
cf. #129
