### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by SirRayne** [ArtemGr/Sidekick#274] opened 2020-12-16 19:17 UTC
It will no longer roll, or do anything. I'm a little disappointed actually. I have Pathfinder tonight, and it's my only dice not right now. I have been using it for months with no issues, but if it isn't fixed, I'll have to find another.

**Comment by elvoreis** [comment] 2020-12-16 19:44
Same issue here. It was working fine yesterday, but today it doesn't doing anything. It's still showing as online and no server changes have been made.

**Comment by ArtemGr** [comment] 2020-12-16 21:12
Duplicate of #232

**Closed by ArtemGr** 2020-12-16 21:12 UTC
